import requests

url = "https://www.linkedin.com/feed/"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    print("Successfully crawled the page!")
    print(response.text[:500])  # Print first 500 characters
else:
    print(f"Error {response.status_code}: Unable to crawl the page")
